include mk/init.mk

SRC_TEST_VALA += test/main.vala test/solution.test.vala src/solution.vala


all: bin/test_vala$(EXEEXT)

clean: clean_details

help: help_details

include mk/targets.mk

