include mk/init.mk

OBJ_TEST_C += src/solution.o test/main.o test/solution.test.o test/test_runners/solution.runner.o

all: bin/test_c$(EXEEXT)

force_cpp: bin/test_cpp$(EXEEXT)

clean: clean_details

include mk/targets.mk

